/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as GrievancesRouteImport } from './routes/grievances'
import { Route as MapViewRouteImport } from './routes/map-view'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AdminAdaptersRouteImport } from './routes/admin.adapters'
import { Route as ProposalsIndexRouteImport } from './routes/proposals.index'
import { Route as ProposalsIdRouteImport } from './routes/proposals.$id'
import { Route as PublicIndexRouteImport } from './routes/public.index'
import { Route as PublicIdRouteImport } from './routes/public.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const GrievancesRoute = GrievancesRouteImport.update({
  id: '/grievances',
  path: '/grievances',
  getParentRoute: () => rootRouteImport,
} as any)
const MapViewRoute = MapViewRouteImport.update({
  id: '/map-view',
  path: '/map-view',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdaptersRoute = AdminAdaptersRouteImport.update({
  id: '/admin/adapters',
  path: '/admin/adapters',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsIndexRoute = ProposalsIndexRouteImport.update({
  id: '/proposals/',
  path: '/proposals/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsIdRoute = ProposalsIdRouteImport.update({
  id: '/proposals/$id',
  path: '/proposals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/public/',
  path: '/public/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIdRoute = PublicIdRouteImport.update({
  id: '/public/$id',
  path: '/public/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/grievances': typeof GrievancesRoute
  '/map-view': typeof MapViewRoute
  '/sign-in': typeof SignInRoute
  '/admin/adapters': typeof AdminAdaptersRoute
  '/proposals/$id': typeof ProposalsIdRoute
  '/public/$id': typeof PublicIdRoute
  '/proposals/': typeof ProposalsIndexRoute
  '/public/': typeof PublicIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/grievances': typeof GrievancesRoute
  '/map-view': typeof MapViewRoute
  '/sign-in': typeof SignInRoute
  '/admin/adapters': typeof AdminAdaptersRoute
  '/proposals/$id': typeof ProposalsIdRoute
  '/public/$id': typeof PublicIdRoute
  '/proposals': typeof ProposalsIndexRoute
  '/public': typeof PublicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/grievances': typeof GrievancesRoute
  '/map-view': typeof MapViewRoute
  '/sign-in': typeof SignInRoute
  '/admin/adapters': typeof AdminAdaptersRoute
  '/proposals/$id': typeof ProposalsIdRoute
  '/public/$id': typeof PublicIdRoute
  '/proposals/': typeof ProposalsIndexRoute
  '/public/': typeof PublicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/grievances'
    | '/map-view'
    | '/sign-in'
    | '/admin/adapters'
    | '/proposals/$id'
    | '/public/$id'
    | '/proposals/'
    | '/public/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/grievances'
    | '/map-view'
    | '/sign-in'
    | '/admin/adapters'
    | '/proposals/$id'
    | '/public/$id'
    | '/proposals'
    | '/public'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/grievances'
    | '/map-view'
    | '/sign-in'
    | '/admin/adapters'
    | '/proposals/$id'
    | '/public/$id'
    | '/proposals/'
    | '/public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  GrievancesRoute: typeof GrievancesRoute
  MapViewRoute: typeof MapViewRoute
  SignInRoute: typeof SignInRoute
  AdminAdaptersRoute: typeof AdminAdaptersRoute
  ProposalsIdRoute: typeof ProposalsIdRoute
  PublicIdRoute: typeof PublicIdRoute
  ProposalsIndexRoute: typeof ProposalsIndexRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grievances': {
      id: '/grievances'
      path: '/grievances'
      fullPath: '/grievances'
      preLoaderRoute: typeof GrievancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map-view': {
      id: '/map-view'
      path: '/map-view'
      fullPath: '/map-view'
      preLoaderRoute: typeof MapViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/adapters': {
      id: '/admin/adapters'
      path: '/admin/adapters'
      fullPath: '/admin/adapters'
      preLoaderRoute: typeof AdminAdaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals/': {
      id: '/proposals/'
      path: '/proposals'
      fullPath: '/proposals/'
      preLoaderRoute: typeof ProposalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals/$id': {
      id: '/proposals/$id'
      path: '/proposals/$id'
      fullPath: '/proposals/$id'
      preLoaderRoute: typeof ProposalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/': {
      id: '/public/'
      path: '/public'
      fullPath: '/public/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/$id': {
      id: '/public/$id'
      path: '/public/$id'
      fullPath: '/public/$id'
      preLoaderRoute: typeof PublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  GrievancesRoute: GrievancesRoute,
  MapViewRoute: MapViewRoute,
  SignInRoute: SignInRoute,
  AdminAdaptersRoute: AdminAdaptersRoute,
  ProposalsIdRoute: ProposalsIdRoute,
  PublicIdRoute: PublicIdRoute,
  ProposalsIndexRoute: ProposalsIndexRoute,
  PublicIndexRoute: PublicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
